#Exercise 1: Hello World
print("hello world")
#Exercise 2: Some Math
result = (99**3)*8
print (result)
#Exercise 3: What is the output?
result = 5 < 3
print(result)
result1 = 3==3
print(result1)
result2 = 3=="3"
print(result2)
result =int("3")> 3
print(result)
result4 = "HELLO" == "hello"
print(result4)
#Exercise 4: Your computer brand
computer_brand = "lenovo"
print(f"ihave a {computer_brand} computer .")
#Exercise 5: Your information
name = "meriem"
age = 23
shoa_size = 38
print(f"my name is {name},i am  {age} years old , i bought new shoa size {shoa_size}.")
#Exercise 6: A & B
a= 19
b= 9
if a > b :
    print("hello world")
#Exercise 7: Odd or Even
number = int(input("enter a number:"))
if number %2==0 :
    print("the number is even.")
else :
    print("the number is odd.") 
    #Exercise 8: What’s your name?
name = input("what is you name?")
if name == "meri":
    print("he!it's me")
else:
    print("hello ! are you good?")
 #Exercise 9: Tall enough to ride a roller coas
    height =int(input("how tall are you en cm ?"))
    height_number =  int(height)

    if height_number > 154:
        print("that states they are tall enough to ride")
    else:
        print("that says they need to grow some more to ride")
